### PR TITLE
Added libgfortran & compilers

### PR DESCRIPTION
**Pull request by nick-youngblut**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nick-youngblut** [comment]
Note: `conda_r_skeleton_helper` did not include `libgfortran`, and the stage-recipes checks didn't catch this issue. I've updated the `meta.yaml` file based on the [r-rje-feedstock](https://github.com/conda-forge/r-rje-feedstock/issues/1)

**Comment by bgruening** [comment]
The libgfortran is an other bug, which we try to solve globally. See here: https://github.com/conda-forge/r-base-feedstock/pull/51

**Comment by nick-youngblut** [comment]
@bgruening thanks for letting me know. Adding `libgfortran` to `run:` in the recipe didn't help with the linux check, so I'm not sure what to do now. Should I wait until you globally solve the libgfortran bug?

**Comment by cbrueffer** [comment]
Restart CI

**Pull request merged**
